version: 2
jobs:
   build:
     working_directory: ~/paho.mqtt.c
     machine: true
     steps:
       - checkout
       #- run: echo "george-edison55-precise-backports" | sudo tee -a /etc/apt/sources.list
       #- run: sudo -E apt-add-repository -y "ppa:george-edison55/precise-backports"
       - run: sudo -E apt-add-repository -y "ppa:mosquitto-dev/mosquitto-ppa"
       - run: sudo -E apt-get -yq update
       - run: sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install cmake cmake-data mosquitto doxygen
       #- run: mosquitto -h
       - run: mosquitto -c test/tls-testing/mosquitto.conf &
       - run:
          command: |
            set -e
            rm -rf build.paho
            mkdir build.paho
            cd build.paho
            echo "travis build dir $CIRCLE_WORKING_DIRECTORY pwd $PWD"
            cmake -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_SAMPLES=TRUE ..
            make
            python ../test/mqttsas2.py 
            ctest -VV --timeout 600
            kill %1
            killall mosquitto